import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled, {css} from "styled-components";
import {AddForm} from "../components/add-form"
import { useEffect, useState } from "react";
import useSWR from "swr";

const fetcher = (resource, init) =>
  fetch(resource, init).then((res) => res.json());

// fetcher-funktion aus dem Hook kopiert

export default function Home() {

const jokes = useSWR("/api/jokes", fetcher);

const [isCreating, setIsCreating] = useState(false);
const [error, setError] = useState();


console.log(jokes)


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CenterElement>
        <h1 className={styles.title}>Jokes! Jokes! Jokes!</h1>
        <AddForm/>
        {jokes.data ? jokes.data.map(element => <OneJoke>{element.name}</OneJoke>) : "loading..."}
        </CenterElement>

      </main>
    </div>
  )
}


const CenterElement = styled.div`
display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
gap:2rem;
padding:1rem;
border-radius:2rem;
background: rgb(205,176,224);
background: linear-gradient(90deg, rgba(205,176,224,1) 0%, rgba(168,224,241,1) 50%, rgba(69,168,252,1) 100%);
`

const OneJoke = styled.div`
list-style:none;
font-size:1.3rem;
`